# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f385e9b72b4ea09de5718759d09f6668c2ff3a6c4367d8e3df37fdfcb5401eb0fd291d3c7a89eb61027be89345cbf5fc5de7f88921be43c99ff8f51bb06cb393

test:
  secret_key_base: 1ccb372baddfc20e04d9345d2d87ecfe41faa4e3f78b507e408f7feb26fe0b184a19620dcea164e6fe4953f85e661e5f4550b9170d739898b70806e3c1395f37

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
